name: Ubuntu CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest
    container: jerryzj/riscv
    steps:
    - uses: actions/checkout@v4
    - name: Build
      # Build your program with the given configuration
      run: |
        python3 scripts/Compiler.py src/forth/system.forth -a src/asm/vm.s -o src/asm/system.s
        make -C src/asm
    - uses: actions/upload-artifact@v4
      with:
        name: my-artifact
        path: |
          ./hello
          src/asm/system.s
  test:
    runs-on: ubuntu-latest
    container: jerryzj/riscv
    steps:
    - uses: actions/checkout@v4
    - name: Download a single artifact
      uses: actions/download-artifact@v4
      with:
        name: my-artifact
    - name: Test
      run: |
        ls
        qemu -h