name: Ubuntu CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Get Dependencies
      run: |
        sudo apt update
        sudo apt install autoconf automake autotools-dev curl python3 libmpc-dev libmpfr-dev libgmp-dev gawk build-essential bison flex texinfo gperf libtool patchutils bc zlib1g-dev libexpat-dev
        mkdir RISCV
        cd RISCV
        git clone --recursive https://github.com/riscv/riscv-gnu-toolchain
        cd riscv-gnu-toolchain
        mkdir build
        cd build 
        ../configure --prefix=/opt/riscv --with-arch=rv32imafdc --with-abi=ilp32
        sudo make -j$(nproc)
        export PATH=/opt/riscv/bin:$PATH


    - name: Build
      # Build your program with the given configuration
      run: |
        cd Stardew
        bash build.sh