name: Ubuntu CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    container: jerryzj/riscv
    steps:
    - uses: actions/checkout@v4
    - name: Build
      # Build your program with the given configuration
      run: |
        python3 scripts/Compiler.py src/forth/system.forth -a src/asm/vm.s -o src/asm/system.s
        make -C src/asm
    - uses: actions/upload-artifact@v4
      with:
        name: my-artifact
        path: |
          ./hello
          src/asm/system.s
  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Set up Environment
      run: |
        sudo apt-get update
        sudo apt-get install -y qemu-system
        sudo apt-get install -y python3-pexpect
        sudo apt-get install python3-pytest
    - uses: actions/checkout@v4
    - name: Download built image
      uses: actions/download-artifact@v4
      with:
        name: my-artifact
    - name: Shuffle files around and test dependencies
      run: |
        ls
        cp ./hello ./scripts
        qemu-system-riscv32 -h
    - name: Run Tests
      run: |
        pytest
        ls
    - uses: actions/upload-artifact@v4
      with:
        name: testlog
        path: |
          ./testlog.txt