name: Ubuntu CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest
    container: msatterthwaite/riscv:riscv_tc
    steps:
    - uses: actions/checkout@v4
    - name: Build
      # Build your program with the given configuration
      run: |
        python3 --version
        python --version
        make -C src/asm
